version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      # Set server type (vs the default of vanilla)
      DEBUG: "false"
      VERSION: 1.20.1
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
    ports:
      - "443:443"
    volumes:
      - ./data:/data
    stdin_open: true
    tty: true
    restart: unless-stopped
volumes:
  data: {}
