version: "3.3"

services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "true"
      # Set server type (vs the default of vanilla)
      DEBUG: "false"
      VERSION: 1.20.1
      TYPE: BUKKIT
      REMOVE_OLD_MODS: "true"
      INIT_MEMORY: 1G
      MAX_MEMORY: 4G
    tty: True
    stdin_open: True
    ports:
      - "443:443"
      - "25575:25575"
    volumes:
      - ./data:/data
      - ./mods:/plugins
    restart: unless-stopped
volumes:
  data: {}
